name: Docker
on:
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
  push:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
    branches-ignore:
      - master
  release:
    types:
      - published
  workflow_dispatch: # This line enables manual triggering
permissions:
  contents: read
jobs:
  ubuntu:
    if: startsWith(github.repository, 'stavdav143/')
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: ["18.04", "20.04", "22.04"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Fetch origin/master from Git
        run: git fetch origin master

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64 # Specify the target platforms
          push: false
          tags: brew
          buildArgs: |
            brew_version="$(git describe --tags --dirty --abbrev=7)"
          labels: |
              org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)"
              org.opencontainers.image.url="https://brew.sh"
              org.opencontainers.image.documentation="https://docs.brew.sh"
              org.opencontainers.image.source="https://github.com/${GITHUB_REPOSITORY}"
              org.opencontainers.image.version="${brew_version}"
              org.opencontainers.image.revision="${GITHUB_SHA}"
              org.opencontainers.image.vendor="${GITHUB_REPOSITORY_OWNER}"
              org.opencontainers.image.licenses="BSD-2-Clause"
      
      - name: Run brew test-bot --only-setup
        run: docker run --rm brew brew test-bot --only-setup

      #- name: Deploy the tagged Docker image to GitHub Packages
      #  if: startsWith(github.ref, 'refs/tags/')
      #  run: |
      #    brew_version="${GITHUB_REF:10}"
      #    echo "brew_version=${brew_version}" >> "${GITHUB_ENV}"
      #    echo ${{secrets.HOMEBREW_BREW_GITHUB_PACKAGES_TOKEN}} | docker login ghcr.io -u BrewTestBot --password-stdin
      #    docker tag brew "ghcr.io/homebrew/ubuntu${{matrix.version}}:${brew_version}"
      #    docker push "ghcr.io/homebrew/ubuntu${{matrix.version}}:${brew_version}"
      #    docker tag brew "ghcr.io/homebrew/ubuntu${{matrix.version}}:latest"
      #    docker push "ghcr.io/homebrew/ubuntu${{matrix.version}}:latest"

      - name: Deploy the tagged Docker image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ${{secrets.STAVDAV_BREW_DOCKER_TOKEN}} | docker login -u stavrosdavaris --password-stdin
          docker tag brew "stavrosdavaris/ubuntu${{matrix.version}}:${brew_version}"
          docker push "stavrosdavaris/ubuntu${{matrix.version}}:${brew_version}"
          docker tag brew "stavrosdavaris/ubuntu${{matrix.version}}:latest"
          docker push "stavrosdavaris/ubuntu${{matrix.version}}:latest"

      #- name: Deploy the homebrew/brew Docker image to GitHub Packages and Docker Hub
      #  if: startsWith(github.ref, 'refs/tags/') && matrix.version == '22.04'
      #  run: |
      #    docker tag brew "ghcr.io/homebrew/brew:${brew_version}"
      #    docker push "ghcr.io/homebrew/brew:${brew_version}"
      #    docker tag brew "ghcr.io/homebrew/brew:latest"
      #    docker push "ghcr.io/homebrew/brew:latest"
      #    docker tag brew "homebrew/brew:${brew_version}"
      #    docker push "homebrew/brew:${brew_version}"
      #    docker tag brew "homebrew/brew:latest"
      #    docker push "homebrew/brew:latest"
